apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: broker-ingress-2
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - http:
        paths:
          - path: /upload
            pathType: ImplementationSpecific
            backend:
              service:
                name: storage
                port:
                  number: 8888
          - path: /car/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: storage
                port:
                  number: 8888
          - path: /auction-data
            pathType: ImplementationSpecific
            backend:
              service:
                name: storage
                port:
                  number: 8888
          - path: /storagerequest/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: storage
                port:
                  number: 8888
          - path: /graphql
            pathType: ImplementationSpecific
            backend:
              service:
                name: gql
                port:
                  number: 5000
          - path: /graphiql
            pathType: ImplementationSpecific
            backend:
              service:
                name: gql
                port:
                  number: 5000

