apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apid.yaml
  - auctioneerd-service.yaml
  - auctioneerd.yaml
  - authd.yaml
  - brokerd.yaml
  - dealerd.yaml
  - gqld.yaml
  - ethd.yaml
  - ingress.yaml
  - ingress2.yaml
  - neard.yaml
  - packerd.yaml
  - piecer.yaml
  - polyd.yaml
  - postgres.yaml
  - relayd.yaml
  - storaged.yaml
